### ISSUE TITLE
Off-by-one doc error

### ISSUE THREAD

**Issue by nirs** [stolostron/multiclusterhub-operator#1204]
Based on https://github.com/stolostron/multiclusterhub-operator/blob/main/docs/installation.md#install-options
there are 4 options to install, but there only 3 in the docmuemnt:
- https://github.com/stolostron/multiclusterhub-operator/blob/main/docs/installation.md#1-run-as-a-deployment-inside-the-cluster
- https://github.com/stolostron/multiclusterhub-operator/blob/main/docs/installation.md#2-run-locally-outside-the-cluster
- https://github.com/stolostron/multiclusterhub-operator/blob/main/docs/installation.md#3-build-and-deploy-catalog-image-to-deploy-operator-via-subscription

**Comment by dislbenn** [comment]
Hi @nirs thank you for identifying this issue. I will create a task in Jira for our squad to begin tracking future updates.

**Comment by dislbenn** [comment]
Will close this issue and continue tracking in Jira.
